### PR TITLE
Added small display on mouseover to check pokemon ID

### PR DESCRIPTION
**Pull request by Sossenbinder**
Added a small display on mouseover to check pokemon ID to clear up confusion on some pokemon which are hard to distinguish like Kadabra or Alkazam. A name would be too long for the div.

### CODE REVIEW

**Comment by waryas** [comment]
How would it work with mobile?

**Comment by Sossenbinder** [comment]
I'm pretty sure it doesn't work on mobile, as :hover needs a pointing device. However, I don't think it's too bad not to have this on mobile, as it could put too much stuff on the UI.

**Comment by FastPokeMapDev** [comment]
Thanks for the input, as another person pointed out, we aim to provide the same experience for both Desktop and Mobile users.
Keep in mind 87% of the user base (about 1M+ users) are mobile users only, so if you can find a way to make this change also benefit the mobile users, it would be great.

**Comment by Sossenbinder** [comment]
Thanks for the feedback, I might be able to work out a solution for mobile. However, I'm not sure if I can debug it, as Leaflet seems to be unresponsive when running the website in device mode in chrome.

**Comment by FastPokeMapDev** [comment]
Yea the dragging doesn't work on Developper mode, most of the developpment is done in theory and just tested on a device.

**Comment by andrewschmitt** [comment]
Would it be possible to implement that feature with an onclick event for a sprite with the class "pokeimg"? That way I believe it should work on both desktop and mobile.

**Comment by Sossenbinder** [comment]
I thought about that too, but I'm not sure if it would interfere with placing the marker

**Comment by FastPokeMapDev** [comment]
It would work but you need to stop propagation of the event. If you make a working code i'll push it to repo then apply to live.

**Comment by Sossenbinder** [comment]
This should work on both mobile and desktop. I don't quite have the tools to test it, but it seemed valid when trying in developer console device mode. 
If I find some time, I might tend to work on a bigger scale solution, effectively displaying a tooltip on click which would be scalable to allow display of details like lat, lng, name and ID without being restricted by the width.

**Comment by waryas** [comment]
Looks good, i'll review code then apply it to test in staging by tomorrow, thanks!

**Pull request merged**
